### ISSUE TITLE
Failed to Upgrade Core with 2.4.0Beta01 version

### ISSUE THREAD

**Issue by irwand** [dakanji/G2Project#68]
I installed 2.4.0Beta01 and executed the Upgrade sequence, and it failed on Upgrade Core step (step 4)

The error is at the end of this message. I did some sleuthing, and it seems that there has been a mistake on the column name that we're updating.
See commit: 18e3032 and 1f5dcdf
So the first commit is connected to this issue: https://github.com/dakanji/G2Project/issues/56
That issue is trying to fix "keyword" limit, and the discussion http://galleryproject.org/node/97957 also talks about the keyword column.

However, the commit is trying to alter Item column, which isn't found. I'm going to update schema.tpl and replace DB_COLUMN_PREFIXItem with DB_COLUMN_PREFIXkeyword and see what happens.

=============== BEGIN ERROR MESSAGE ===========
(mysqli): DROP INDEX g2_Item_99070 ON g2_Item   

mysqli error: [1054: Unknown column 'g_Item' in 'g2_Item'] in
EXECUTE("ALTER TABLE g2_Item
  MODIFY COLUMN g_Item text")

(mysqli): ALTER TABLE g2_Item
  MODIFY COLUMN g_Item text   

Query: ALTER TABLE g2_Item
  MODIFY COLUMN g_Item text failed. Unknown column 'g_Item' in
'g2_Item'

1054: Unknown column 'g_Item' in 'g2_Item'

---

ADOConnection._Execute(ALTER TABLE g2_Item
  MODIFY COLUMN g_Item text, false) %
line  891, file: adodb.inc.php
                  ADOConnection.Execute(ALTER TABLE g2_Item
  MODIFY COLUMN g_Item text) % line
1703, file: GalleryStorageExtras.class
               GalleryStorageExtras._executeSql(DROP INDEX
DB_TABLE_PREFIXItem_99070 ON DB_TABLE_PREFIXItem;

ALTER TABLE DB_TABLE_PREFIXItem
  MODIFY COLUMN DB_COLUMN_PREFIXIt...) %
line 1363, file: GalleryStorageExtras.class
            GalleryStorageExtras.configureStore(core,
Array[1]) % line  769, file: GalleryStorage.class
         GalleryStorage.configureStore(core, Array[1]) % line 2564, file: CoreModuleExtras.inc

realpath(/home/irwand/src/G2Project/modules/core/classes/../../../)
realpath(/home/irwand/src/G2Project/)
Error: Failed to upgrade the core module, this is the error stack trace:
Error (ERROR_STORAGE_FAILURE) :
/home/irwand/src/G2Project/modules/core/classes/GalleryStorage/GalleryStorageExtras.class
in modules/core/classes/GalleryStorage/GalleryStorageExtras.class
at line 1707 (GalleryCoreApi::error) 
in modules/core/classes/GalleryStorage/GalleryStorageExtras.class
at line 1363 (GalleryStorageExtras::_executeSql) 
in modules/core/classes/GalleryStorage.class at line 769
(GalleryStorageExtras::configureStore) 
in modules/core/CoreModuleExtras.inc at line 2564
(GalleryStorage::configureStore) 
in modules/core/module.inc at line 497
(CoreModuleExtras::upgrade) 
in modules/core/classes/GalleryModule.class at line 154
(CoreModule::upgrade) 
in upgrade/steps/UpgradeCoreModuleStep.class at line 85
(GalleryModule::installOrUpgrade) 
in upgrade/index.php at line 186
(UpgradeCoreModuleStep::processRequest) 

realpath(/home/irwand/src/G2Project/modules/core/classes/../../../)
realpath(/home/irwand/src/G2Project/)

**Comment by dakanji** [comment]
Hi.

Thanks for having a punt.
 I am currently travelling away from my dev machine. Will have a look at these later

**Comment by irwand** [comment]
It's cool, take your time.
I replaced DB_COLUMN_PREFIXItem with DB_COLUMN_PREFIXkeyword, and I managed to get passed Upgrading Core Module step. On the next one, 2 modules failed to upgrade.

At this point, I wonder if I would continue using G2. It looks like I might just migrate to piwigo. Honestly I like G2 better, but I don't have that much time to figure out how to move this code base to php7. I'm not familiar with php to begin with.

**Comment by dakanji** [comment]
In that case, I will suggest trying an alternative instead as there is
quite a lot to do on G2 and will take quite a bit of time and effort to get
there.

**Comment by irwand** [comment]
Yeah, that's what I'm discovering. Surprisingly, it's not that difficult to migrate to piwigo. There's menalto2piwigo extension that helps a bunch.
Thank you much! You have a great day!

**Comment by dakanji** [comment]
The v240-Base branch should be PHP 7 compartible
